apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: o11y
spec:
  selector:
    matchLabels:
      app: prometheus
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          args:
            - --web.enable-remote-write-receiver
            - --storage.tsdb.path=/prometheus/
            - --config.file=/etc/prometheus/prometheus.yml
          ports:
            - name: http
              containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus
            - name: prometheus-storage-volume
              mountPath: /prometheus
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
            defaultMode: 420
        - name: prometheus-storage-volume
          emptyDir:
            sizeLimit: 500Mi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: o11y
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: o11y
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: http

