apiVersion: apps/v1
kind: Deployment
metadata:
  name: jsonapi
  namespace: app
spec:
  selector:
    matchLabels:
      app: jsonapi
  replicas: 1
  template:
    metadata:
      labels:
        app: jsonapi
    spec:
      containers:
        - name: jsonapi
          image: ghcr.io/slarwise/jsonapi:latest
          ports:
            - name: http
              containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: jsonapi
  namespace: app
spec:
  selector:
    app: jsonapi
  ports:
  - protocol: TCP
    port: 3000
    targetPort: http
  type: LoadBalancer
